enhancement:
  - head-branch: ['^task/', '^feat/', '^feature/']

bug:
  - head-branch: ['^bug/', '^fix/']

refactoring:
  - head-branch: ['^refactor/']

performance:
  - head-branch: ['^perf/']

documentation:
  - head-branch: ['^docs/']
  - changed-files:
      - any-glob-to-any-file:
          - 'README.md'

ci-cd:
  - head-branch: ['^ci/']
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - 'Dockerfile'
          - '.dockerignore'
          - 'mise.toml'
          - 'lefthook.yml'

testing:
  - head-branch: ['^test/']
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.spec.ts'
          - '**/*.test.ts'
          - 'e2e/**'
          - 'playwright.config.ts'
          - 'vite.config.ts'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'package-lock.json'
